apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: pregod-hub
  namespace: pregod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pregod-hub
  minReplicas: 4
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageUtilization
        averageUtilization: 70
